color = input("Enter a color: ")
pluralNoun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity (that rhymes with color): ")
print("Roses are " + color)
print(pluralNoun + " are blue, it's true!")
print("I love " + celebrity)
print("And so do you!")
