phrase = "Giraffe Academy"
print("\"Giraffe Academy\"")
print(phrase + " is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[3])
print(phrase.index("G"))
print(phrase.index("Academy"))
print(phrase.replace("Giraffe", "Tiger"))
